### ISSUE TITLE
Sujet incoherent

### ISSUE THREAD

**Issue by agagniere** [42Paris/Challenge-HotRace#2]
Page 4, en haut :
> "Il n'y a pas besoin de bien free"

Page 7, dernière consigne :
> "Toute mémoire allouée sur le tas doit être libérée proprement."

Je pense comprendre qu'on ne doit pas leak pendant l'utilisation du programme, mais qu'on a le droit de ne pas free après reception de EOF. Mais en l'état le sujet n'est pas cohérent.

**Comment by ghost** [comment]
Hello,

merci pour ton issue, c'est exactement ca
